image: maven:latest
cache:
  paths:
    - target/
    - .m2/

stages:
    - build
    - package
    
build:
  stage: build
  script:
    - mvn compile


package:
  stage: package
  script:
    - mvn package
  artifacts:
    paths: 
      - target/injectenvbeforescm.hpi
  only:
    - master